### ISSUE TITLE
Failure to clone repository on Windows based filesystems

### ISSUE THREAD

**Issue by hova0** [hyperledger/fabric-ca#1]
When attempting to clone or fetch the current repository at commit 88949898ad38a4c946ec21180c0b013542a8c465
the following files fail to download due to ":" being in the filename which is illegal on Windows based filesystems:

vendor/github.com/cloudflare/cfssl/vendor/github.com/cloudflare/cfssl_trust/ca-bundle/SwissSignCA(RSAIKMay6199918:00:58)_2000-11-26_SHA1WithRSA.crt
 vendor/github.com/cloudflare/cfssl/vendor/github.com/cloudflare/cfssl_trust/ca-bundle/SwissSignCA(RSAIKMay6199918:00:58)_2000-11-26_SHA1WithRSA_2.crt

**Comment by rjones-lf** [comment]
Hello, thank you for your report!
This is a read-only mirror. I've copied your issue to [JIRA](https://jira.hyperledger.org/browse/FAB-1854).
