### ISSUE TITLE
fabric-ca package binary is not available in release 1.5.0

### ISSUE THREAD

**Issue by gangadharjannu** [hyperledger/fabric-ca#245]
## What is the issue?

It seems like fabric-ca packages for linux and windows are missing in release v1.5.0

## What is causing issue?

While setting fabric network using the command `curl -sSL https://bit.ly/2ysbOFE | bash -s ` is trying to install fabric-ca package 1.5.0 for linux and since it is not available script is throwing error

```
==> Cloning hyperledger/fabric-samples repo
Cloning into 'fabric-samples'...
remote: Enumerating objects: 7688, done.
remote: Total 7688 (delta 0), reused 0 (delta 0), pack-reused 7688
Receiving objects: 100% (7688/7688), 4.50 MiB | 18.43 MiB/s, done.
Resolving deltas: 100% (4020/4020), done.
fabric-samples v2.3.2 does not exist, defaulting main

Pull Hyperledger Fabric binaries

===> Downloading version 2.3.2 platform specific fabric binaries
===> Downloading:  https://github.com/hyperledger/fabric/releases/download/v2.3.2/hyperledger-fabric-linux-amd64-2.3.2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   649  100   649    0     0   3294      0 --:--:-- --:--:-- --:--:--  3294
100 73.5M  100 73.5M    0     0  33.1M      0  0:00:02  0:00:02 --:--:-- 40.3M
==> Done.
===> Downloading version 1.5.0 platform specific fabric-ca-client binary
===> Downloading:  https://github.com/hyperledger/fabric-ca/releases/download/v1.5.0/hyperledger-fabric-ca-linux-amd64-1.5.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     47      0 --:--:-- --:--:-- --:--:--    47

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
==> There was an error downloading the binary file.

------> 1.5.0 fabric-ca-client binary is not available to download  (Available from 1.1.0-rc1) <----
```

## Platform
Ubuntu Linux

## How long you were experience this ?

It was working two days ago but since this morning it is suddenly stopped working. It seems the new release 1.5.1 which released on August 16 may have something to do with this

## difference between v1.5.0 and v1.5.1

First image is 1.5.0 and second image is 1.5.1

<img width="423" title="1.5.0" alt="Screenshot 2021-08-18 at 14 53 34" src="https://user-images.githubusercontent.com/7323026/129901474-3b77b26c-f6f4-49fb-abbf-619589e92145.png">

<img width="430" title="1.5.1" alt="Screenshot 2021-08-18 at 14 54 16" src="https://user-images.githubusercontent.com/7323026/129901564-d1550eb1-cd68-4de8-a743-3f46c7af5056.png">

**Comment by davidkel** [comment]
@gangadharjannu The script that the curl command references should now be updated to pull down the 1.5.1 ca binaries. Could you check and make sure it works for you and update this issue with your findings

**Comment by gangadharjannu** [comment]
@davidkel Yes, I tested now and it is working 🥳 

Script is able to fetch fabric-ca 1.5.1 for linux 

Thanks for the quick resolution :)

For all others, 

You don't need to do anything extra, running `curl -sSL https://bit.ly/2ysbOFE | bash -s` command to setup fabric network now works by pulling fabric 2.3.2 and fabric-ca 1.5.1
