### ISSUE TITLE
Link for 1.5.0 Linux binaries is broken

### ISSUE THREAD

**Issue by pdmendki** [hyperledger/fabric-ca#251]
Linux binaries for 1.5.0 were available here
https://github.com/hyperledger/fabric-ca/releases/download/v1.5.0/hyperledger-fabric-ca-linux-amd64-1.5.0.tar.gz
This link is broken now

**Comment by mastersingh24** [comment]
I think there was an issue with the binaries.  You should use the 1.5.1 binaries which are now available.
