### ISSUE TITLE
fabric-ca-server linux binary doesn't run on Ubuntu 18.04

### ISSUE THREAD

**Issue by davidkel** [hyperledger/fabric-ca#264]
The fabric-ca-server has a dependency on glibc 2.28, so when trying to run it you get
```
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by bin/fabric-ca-server)
```

The problem is likely because the binary has been built on a much newer version of ubuntu (possibly 20.04) but by doing so means it cannot be used on older LTS versions of ubuntu and is likely to be a problem for other distros as well.

**Comment by denyeart** [comment]
@davidkel
Do you know where the dependency comes from?
Do you expect the problem is isolated to fabric-ca-server and not any other fabric binary?

**Comment by davidkel** [comment]
@denyeart the dependency I believe comes from compiling it on ubuntu 20.04 and because fabric-ca-server requires CGO which pulls in the c runtime library (so this is why it doesn't affect the other binaries). I would need to check but if you compile it on an earlier version of ubuntu then it would work on that version and newer versions. The binary however would not work necessarily on other linux systems (eg alpine because of their use of a different c runtime), and depending on the c runtime used by the system you compile on will control which versions of other linux distros it will work on
