### ISSUE TITLE
Permission issue when running docker container with non-root user

### ISSUE THREAD

**Issue by RuiSiang** [hyperledger/fabric-ca#265]
## Summary
fs permission issue in docker container when attempting to run with a non-root user

## Steps to reproduce
`docker run -d --user 1000:1000 hyperledger/fabric-ca:1.5.0`

## Enviroment
* os: ubuntu 20.04
* docker version: 20.10.5
* image version: hyperledger/fabric-ca:1.5.0

## Expected behavior
functional fabric-ca container with port 7054 exposed

## Resulted behavior
container exited with following error: `Error: Failed to create default configuration file: mkdir /etc/hyperledger: permission denied`

## Possible cause
due to how the image is built, directory/files required to run fabric-ca-server are owned by root

**Comment by mastersingh24** [comment]
@RuiSiang  - You can use the `--home` flag to override the default home directory and choose a directory for which user `1000:1000` has permissions.  If they directory path does not exist, then the user will need create directory permissions.

**Comment by RuiSiang** [comment]
Thank you!!
