### ISSUE TITLE
Interoperability tests are failing with latest CA updates

### ISSUE THREAD

**Issue by jkneubuh** [hyperledger/fabric-ca#309]
PR #304 introduced a regression in the Node and Java SDK client libraries, as it altered the folder structures expected by the test suites and SDK client applications.

[example test failure](https://dev.azure.com/Hyperledger/Fabric-Test/_build/results?buildId=54234&view=results)

Address this by reverting PR 304 and pushing the new folder structure updates into the Token/Smart Client SDKs.

**Comment by denyeart** [comment]
Fixed with #308
