### ISSUE TITLE
Hyperledger's BCCSP is failing to initialize with our PKCS11 package.

### ISSUE THREAD

**Issue by kiran-m-kannur** [hyperledger/fabric-ca#312]
We're trying to use Fortanix PKCS11 library with hyperledger.
Here is some information about the pkcs11 tool :
`Cryptoki version 3.0 `
`Manufacturer     Fortanix`
`Library          Fortanix Data Security Manager PKCS11 Library (ver 0.3)`
`Using slot 0 with a present token (0x1)`

The hyper ledger's BCCSP is failing to initialize with Fortanix PKCS11 (Error: Failed to get BCCSP with opts: Could not initialize BCCSP PKCS11: pkcs11: instantiation failed for /etc/hyperledger/fabric/fortanix_pkcs11_4.8.2070.so)
We have modified the base image to centos, and the pkcs11 tool works with our library as well. 

We have made the following changes to the fabric-ca-server-config.yaml file:
`bccsp:`
`    default: PKCS11`
`    pkcs11:`
`         Library: /home/ccm-user/fortanix_pkcs11/fortanix_pkcs11_4.2.1500.so`
`        Pin: file:///home/ccm-user/fortanix_pkcs11/pkcs11.conf`
`         label: "Fortanix Token"`
`         hash: SHA2`
`         security: 256`

And the config file contains : 

`api_endpoint = "https://sdkms.fortanix.com"`
`api_key="xxxxxx"`
`app_id="xxxxxxx"`
`[log]`
`system = true # Unix only, logs to syslog`

Is there any other changes that need to be done in the BCCSP section to integrate our library with the hyperledger fabric?

**Comment by davidkel** [comment]
The error suggests an issue with loading ` /etc/hyperledger/fabric/fortanix_pkcs11_4.8.2070.so`. Possible issues could be that the file doesn't exist, it's not a valid binary (eg wrong architecture), it can't load it's dependencies. Unfortunately fabric doesn't capture the cause, so you need to determine the cause yourself. I've not tried it but you could look at the LD_DEBUG environment variable as a way to get more information for example as well as trying cli tools such as ldd.

**Comment by kiran-m-kannur** [comment]
The package is a valid and it works when used with the pkcs11-tool(opensc) inside the container environment. And also the ldd shows no breaking dependencies 
`linux-vdso.so.1 =>  (0x00007ffdf40de000)`
`libdl.so.2 => /lib64/libdl.so.2 (0x00007f89bc2ef000)`
`librt.so.1 => /lib64/librt.so.1 (0x00007f89bc0e7000)`
`libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f89bbecb000)`
`libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f89bbcb5000)`
`libc.so.6 => /lib64/libc.so.6 (0x00007f89bb8e7000)`
`/lib64/ld-linux-x86-64.so.2 (0x00007f89bd1c3000)`
`libm.so.6 => /lib64/libm.so.6 (0x00007f89bb5e5000)`

**Comment by kiran-m-kannur** [comment]
Yes, we did try that and it shows no breaking dependencies. The [pkcs11](https://github.com/miekg/pkcs11) package that the fabric uses is able to load with fortanix pkcs11 lib as well. We tested this by using the wrapper code given in the example section of [pkcs11](https://github.com/miekg/pkcs11).
