### ISSUE TITLE
Possible error on YAML file 

### ISSUE THREAD

**Issue by anagnostouJohn** [hyperledger/fabric-ca#345]
I think is an error on ` configtx.yaml` file At AnchorPeers should be  - Port: 7051 instead of  Port: 7051

```
- &org1

   Name: org1

   ID: org1MSP

   MSPDir: /tmp/hyperledger/org1/msp

   AnchorPeers:
      - Host: peer1-org1
         Port: 7051
```
```
- &org1

   Name: org1

   ID: org1MSP

   MSPDir: /tmp/hyperledger/org1/msp

   AnchorPeers:
      - Host: peer1-org1
      - Port: 7051
```

**Comment by denyeart** [comment]
Actually it is correct... it is a single object with two key/value pairs (Host and Port), therefore one dash is correct.

See the reference example in fabric repository:
https://github.com/hyperledger/fabric/blob/main/sampleconfig/configtx.yaml
