### ISSUE TITLE
fabric-ca-client and fabric-ca-server build fails on s390x in v1.5.7  - likely due to commit d575f40e

### ISSUE THREAD

**Issue by silliman** [hyperledger/fabric-ca#373]
My builds of fabric-ca-client and fabric-ca-server on s390x (for both native binary and Docker image) are failing with Fabric-ca release v1.5.7.  They succeeded in v.1.5.6.  The builds appear to have broken after commit d575f40e which changed the mathlib dependency.  (Things work with the commit immediately prior to d575f40e).

Here are some commands that show my environment and the steps to reproduce the error.  Error is shown for the fabric-ca-client native build failure- similar error occurs for fabric-ca-server native build and for docker image build.

```
barry@fabric01:~/go/src/github.com/silliman/fabric-ca$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

barry@fabric01:~/go/src/github.com/silliman/fabric-ca$ uname -a
Linux fabric01 5.4.0-159-generic #176-Ubuntu SMP Mon Aug 14 12:03:34 UTC 2023 s390x s390x s390x GNU/Linux

barry@fabric01:~/go/src/github.com/silliman/fabric-ca$ go version
go version go1.20.7 linux/s390x

barry@fabric01:~/go/src/github.com/silliman/fabric-ca$ git checkout v1.5.7
Previous HEAD position was d575f40e This PR brings the following: - prepare the revocation handle as expected by the idemix lib - idemix: export revocation handle in SignerConfig - update idemix and mathlib dep - add logs to idemix issuer - doc update
HEAD is now at 86c6b463 Release commit for v1.5.7

barry@fabric01:~/go/src/github.com/silliman/fabric-ca$ make fabric-ca-client
Building fabric-ca-client in bin directory ...
# github.com/IBM/mathlib/driver/kilic
vendor/github.com/IBM/mathlib/driver/kilic/custom.go:137:2: undefined: mul
vendor/github.com/IBM/mathlib/driver/kilic/custom.go:148:2: undefined: mul
vendor/github.com/IBM/mathlib/driver/kilic/custom.go:152:2: undefined: mul
vendor/github.com/IBM/mathlib/driver/kilic/custom.go:155:2: undefined: mul
vendor/github.com/IBM/mathlib/driver/kilic/custom.go:156:2: undefined: mul
vendor/github.com/IBM/mathlib/driver/kilic/custom.go:158:2: undefined: mul
vendor/github.com/IBM/mathlib/driver/kilic/custom.go:327:2: undefined: mul
make: *** [Makefile:106: bin/fabric-ca-client] Error 1

barry@fabric01:~/go/src/github.com/silliman/fabric-ca$ git checkout v1.5.6
Previous HEAD position was 86c6b463 Release commit for v1.5.7
HEAD is now at 47a32f27 Release commit for v1.5.6 (#358)

barry@fabric01:~/go/src/github.com/silliman/fabric-ca$ make fabric-ca-client
Building fabric-ca-client in bin directory ...
Built bin/fabric-ca-client
```

**Comment by denyeart** [comment]
A recent github.com/IBM/mathlib update introduced an architecture specific build tag.

I see that a "generic" implementation for mul() is available here:
https://github.com/IBM/mathlib/blob/main/driver/kilic/custom_generic.go#L53

This file has a build tag of `//go:build !amd64 || generic`:
https://github.com/IBM/mathlib/blob/main/driver/kilic/custom_generic.go#L1

Based on that build constraint, I would expect architectures besides amd64 to use the generic implementation automatically. But maybe the "generic" build tag needs to be explicitly passed?

@ale-linux Any ideas? What was the intent for architectures besides amd64?

**Comment by denyeart** [comment]
Thanks to @ale-linux investigation, we found that updating github.com/IBM/mathlib to `v0.0.3-0.20231011094432-44ee0eb539da` resolves the problem.

Note that it can be tested on other platforms by doing:

`env GOOS=linux GOARCH=s390x make clean fabric-ca-server`
and
`env GOOS=linux GOARCH=s390x make clean fabric-ca-server`

**Comment by denyeart** [comment]
@silliman @asararatnakar @benjsmi Fix has been merged into fabric-ca main branch. Can you try a s390x build from main branch, and if it looks good, we can release v1.5.8 with the fix.

**Comment by asararatnakar** [comment]
@denyeart Thank you for the follow up Dave. We were able to build s390x from main branch.

**Comment by silliman** [comment]
This builds fine now on s390x.   I successfully ran the fabric-samples/test-network (with -ca argument) with the built fabric-ca OCI image. Thanks for the fix!
