### ISSUE TITLE
S3 or DB support

### ISSUE THREAD

**Issue by alidehghan** [hyperledger/fabric-ca#375]
Hello,

Is there any possibility to store (and retrieve) cert files on S3 or DB instead of traditional filesystem basis?

this filesystem mechanism is neither safe and scalable.

**Comment by denyeart** [comment]
The recommendation for a more secured environment is to use a Hardware Security Module (HSM):
https://hyperledger-fabric.readthedocs.io/en/latest/hsm.html#using-an-hsm-with-a-fabric-ca

**Comment by alidehghan** [comment]
HSM is more secure but not convenient, apart from that, a distributed way is still needed for handling certs
